### ISSUE TITLE
Trice does not respect comments

### ISSUE THREAD

**Issue by ryceg** [incobalt/Trice#1]
Commenting out lines of code tagged as [grammar] does not disable them from being parsed.

**Comment by incobalt** [comment]
That's probably correct, I'll take a look at this over the weekend and provide an update. I can certainly see why people might want to comment their grammar passages! I'll work on support for /* */  /% %/ and , which are what Sugar Cube allow. I should also be able to do // style comments, I think.

**Comment by ryceg** [comment]
That would be amazing! Thanks very much :)

**Comment by incobalt** [comment]
I just put in an update that should have this working now! I updated the readme with information about comments and have added some comments to the gHabitatFeature passage of TriceExample.html. As an added bonus, grammar passages now ignore blank lines, so you can space out your rules if you like. Let me know if you encounter any problems!
